package com.project.singk.mock;

import com.project.singk.domain.comment.domain.CommentSimplified;
import com.project.singk.domain.comment.domain.RecommendComment;
import com.project.singk.domain.comment.service.port.RecommendCommentRepository;
import com.project.singk.global.api.ApiException;
import com.project.singk.global.api.AppHttpStatus;

import java.util.*;
import java.util.concurrent.atomic.AtomicLong;

public class FakeRecommendCommentRepository implements RecommendCommentRepository {
	private final AtomicLong autoGeneratedId = new AtomicLong(0);
	private final List<RecommendComment> data = Collections.synchronizedList(new ArrayList<>());

    @Override
    public RecommendComment save(RecommendComment recommendComment) {
        if (recommendComment.getId() == null || recommendComment.getId() == 0) {
            RecommendComment newRecommendComment = RecommendComment.builder()
                    .id(autoGeneratedId.incrementAndGet())
                    .parentId(recommendComment.getParentId())
                    .content(recommendComment.getContent())
                    .likes(recommendComment.getLikes())
                    .member(recommendComment.getMember())
                    .post(recommendComment.getPost())
                    .createdAt(recommendComment.getCreatedAt())
                    .modifiedAt(recommendComment.getModifiedAt())
                    .build();
            data.add(newRecommendComment);
            return newRecommendComment;
        } else {
            data.removeIf(item -> Objects.equals(item.getId(), recommendComment.getId()));
            data.add(recommendComment);
            return recommendComment;
        }
    }

    @Override
    public RecommendComment getById(Long id) {
        return findById(id).orElseThrow(() -> new ApiException(AppHttpStatus.NOT_FOUND_COMMENT));
    }

    @Override
    public Optional<RecommendComment> findById(Long id) {
        return data.stream().filter(item -> item.getId().equals(id)).findAny();
    }


    @Override
    public void deleteById(Long commentId) {
        data.removeIf(item -> item.getId().equals(commentId));
    }

    @Override
    public void deleteByPostId(Long postId) {
        data.removeIf(item -> item.getPost().getId().equals(postId));
    }

    @Override
    public List<CommentSimplified> findAllByPostId(Long postId) {
        return data.stream()
                .filter(item -> item.getPost().getId().equals(postId))
                .map(this::simplified)
                .toList();
    }

    @Override
    public List<CommentSimplified> findAllByMemberId(Long memberId) {
        return data.stream()
                .filter(item -> item.getMember().getId().equals(memberId))
                .map(this::simplified)
                .toList();
    }

    private CommentSimplified simplified(RecommendComment comment) {
        return CommentSimplified.builder()
                .id(comment.getId())
                .parentId(comment.getParentId())
                .content(comment.getContent())
                .likes(comment.getLikes())
                .member(comment.getMember())
                .createdAt(comment.getCreatedAt())
                .modifiedAt(comment.getModifiedAt())
                .build();
    }
}
