name: Deploy to Amazon EC2

on:
  push:
    branches: [ "main", "develop" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    # (1) 기본 체크아웃
    - name: Checkout
      uses: actions/checkout@v3
    
    # (2) Docker 이미지 빌드
    - name: Docker Image Build for Dev version
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/singk-web-dev .
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/singk-web-dev

    # (3) EC2 ssh 접속 및 컨테이너 실행
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEV_EC2_HOST }}
        username: ${{ secrets.DEV_EC2_USERNAME }}
        port: 22
        key: ${{ secrets.DEV_EC2_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/singk-web-dev
          cd ~/dockers
          echo "${{ secrets.APPLICATION_SECRET }}" > ./config/application-secret.yml
          docker-compose down
          docker-compose up -d
          docker image prune -f
